### PR TITLE
Added Streets of Tarkov svg map

### PR DESCRIPTION
**Pull request by Shebuka**
Based on the Jindouz map

### CODE REVIEW

**Comment by Shebuka** [comment]
@thaddeus how difficult/time-consuming will it be to add the quest objectives to the map?

**Comment by thaddeus** [comment]
@Shebuka Not trivial, but not terrible. I have a WIP editor to fill in data that isn't natively part of tarkov.dev API, which right now is just the GPS data plus some locations that were off when I launched TT3. https://tarkovtracker.io/taskeditor This uses local storage to create a data structure which is stored in https://github.com/TarkovTracker/tarkovdata/blob/master/objective_gps.json I forget if I pull the existing data when the editor is loaded or if that would need to be copied in before you start adding the new stuff to make integrating it easier

**Comment by thaddeus** [comment]
Took a quick peek at this, its great! I need to double check layer names and stuff a little later (I really want to get to the point that all the maps have identical names for layers (or patterned) such that you can easily programmatically add/remove things depending upon what you're trying to use the map for. Should get back to this tonight

**Review by thaddeus — APPROVED** [review]
LGTM 👍 Thanks!

**Pull request merged**
