### PR TITLE
Reserve svg and illustrator map

### PR DESCRIPTION
**Pull request by TheGlu3guy**
Created a Reserve map and added 2 svg of it :
- Reserve.svg : the map without the basement
- ReserveBasement.svg : the map with 2 layers, the floor and the basement.
And the .ai.

### CODE REVIEW

**Comment by kokarn** [comment]
Looks very good overall!

We are trying to get the new svgs with the correct cardinal directions, eg north up on the map. 
Sadly most of the old ones are wrong, so they are a bad reference.

Here's one that _should_ be correct but haven't validated in game
reserveMap

**Comment by TheGlu3guy** [comment]
Oh ok, so I just need to flip it ?

Ps : I am still beginning with github and it's my first time participating to an open source project

**Comment by TheGlu3guy** [comment]
Ok it commited with my other account but at least it is rotated now

**Review by thaddeus — APPROVED** [review]
👍 Thanks for making this and contributing! Looks good! After this is merged, I'm going to change up the parent level layers (ground level and basement, I need to rework something slightly on default layers) to match the other maps, and will add the quest locations to the quest data file this weekend.

**Pull request merged**
