### PR TITLE
Group names for floors must be unique

### PR DESCRIPTION
**Pull request by Shebuka**
Adding a "Connector" suffix to connector group named same as floors. They are so-called connector groups that were named the same as the floor they were connecting. My suspect is that TarkovTool only toggled alpha for the most inner XML group name (that happen to be these connectors e.g. stairs) and not the actual floor.

Probable (can't test, but seems reasonable) fix for #195

### CODE REVIEW

**Comment by Shebuka** [comment]
@thaddeus can you verify this?

**Comment by thaddeus** [comment]
Sorry - will check this out tomorrow evening to verify this works - thanks for tracking this down!

**Comment by Shebuka** [comment]
This is just a ping 😃

**Review by thaddeus — APPROVED** [review]

**Comment by Shebuka** [comment]
We probably have also an issue with the code of D3 selector itself in TarkovMap.vue, see #203

**Pull request merged**
