### PR TITLE
Update item_presets.json to match shortNames

### PR DESCRIPTION
**Pull request by kokarn**
My understanding is that the default presets should have the weapons shortName as name. This updates that.

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
This looks right, except the DVL default preset does change the item's name so I think Urbana should remain.

The names given here are mostly to make it human-readable. I would not recommend doing any matching based on the name fields. I think the weapon size calculator might use shortname matching to find default presets, but if so, that was written before the "default" flag was added here and I should re-write how the calculator works. 

From a consistency standpoint, the shortname isn't what the game always displays anyway. Wherever it would display the shortname for an item, it displays the base item shortname and then appends the appendName value (connected by a space). Where it would display the full item name (e.g., when you double-click a weapon), then it displays the full item name plus the appendName value.

**Comment by kokarn** [comment]
So what is your suggestion for the name field? To use the shortName or something else?

**Comment by Razzmatazzz** [comment]
Using shortName here is fine just for readability purposes. I just wouldn't use the preset's name value for any other naming/matching purposes.

**Comment by kokarn** [comment]
So merge as is or does DVL need a fix?

**Comment by Razzmatazzz** [comment]
I'm not sure, to be honest. That's a weird edge case where the default preset actually changes the name of the weapon. I think with all the other non-default presets, the name represents the weapons shortname + the appendName value (or at least they did initially before some weapon shortnames changed). With the other default presets, the preset name matches the weapon shortname (and there is no appendName value).

On the one hand, keeping the "standard" shortname further signals that it's a default preset (and arguably, the presence of an appendName value also signals that the default preset changes the name of the weapon). On the other hand, the names in this file are roughly meant to equate to the final shortnames shown in the game for these presets. But given that weapon shortnames can and do change, it seems likely that these names will become out of sync anyway.

**Review by Razzmatazzz — APPROVED** [review]
LGTM

**Pull request merged**
