### PR TITLE
'Arbitrary' + BSG Ids for Quests, and update items.en.json

### PR DESCRIPTION
**Pull request by thaddeus**
So, I've been working on TarkovTracker/TarkovTracker#12 to utilize the UUID changes, but realized there's a couple things I'm hitting.

1) TarkovTracker's use of the Ids is how progresss is stored. I could in theory go through and migrate all of the online progress data to the new UUIDs, but I wouldn't be able to solve that for the offline users. That's my fault and my problem, but there's a second point I'll get to.
2) When new quests are added, to the best of my knowledge, acquiring these BSG Ids means decompiling the game source (I believe that was done by someone else and then passed along). That's something that I have two issues with, that's not something I know how to do myself, and secondly I don't know how long it would take to get the new ID.

So my solution is to move the BSG UUIDs to their own field `gameId` and revert the old Id field to the previous values. It would be fantastic if we had ready access to this kind of data direct from BSG, but I realize that would be complicated for things like 'hidden' quests.

The second change I made, was I noticed things like 'Ratchet Wrench' weren't in the `items.en.json` file, so I pulled the latest set of data from @kokarn's GraphQL. 

The third change is updating the hideout.json file to utilize the BSG UUIDS for items.

The final change was changing 'tool' objectives like placing MS2000 Markers or Signal Jammers with their item UUID

### CODE REVIEW

**Comment by kokarn** [comment]
Looks good! And it's for sure the problem with no official BSG API to query data directly from.

Maybe this brings up an even greater question; 
what is the use of having BSG quest IDs?

**Comment by thaddeus** [comment]
@kokarn I think having the BSG Ids can be useful in terms of allowing any tool utilizing this data to communicate with other tools that also have the UUIDs associated. In theory this could be useful to standardize things like marking quest completion on Tarkov Tracker from external tools like RatScanner.

Either way, I finished updating the tools with their appropriate item UUIDs, can you give the PR a review when you have a moment?

**Review by kokarn — APPROVED** [review]
Looks good. Very hard to examine in full :/

**Comment by thaddeus** [comment]
@kokarn Fair. I've been thinking about solutions. Almost like the repo needs a super basic data explorer that would work generically and in PRs.

**Pull request merged**
