### PR TITLE
Added data files for #24 & #25

### PR DESCRIPTION
**Pull request by Filodoxia**
Created the trader data file. Chose to not use an array but an object as top level structure, so you can refer to traders by `traders['prapor']` instead of having to filter the array. If you need an array you could simply use `Array.from()`, I guess.

Data taken from the wiki.

### CODE REVIEW

**Comment by Filodoxia** [comment]
Wasn't aware that pull request are per branch and not on commit basis. So I'll just use this pull request for both new data files (traders & maps), because there isn't much complexity to this and the comment regarding the trader data file format applies to the map data file as well.

**Comment by kokarn** [comment]
Looks really good! One thing I'm not a huge fan of is the shortened names like "reqReputation"

Doesn't really serve a purpose to make it shortened

**Comment by Filodoxia** [comment]
100% agree. I just went of the example given in the issue where we had `rep` and `salesCur` and I already felt guilty to make the names this long.

**Comment by kokarn** [comment]
Yeah, there are for sure improvements to be made in multiple places. 
But as this is new raw data we can be thorough! 

Anything else you feel you could improve on?

**Comment by Filodoxia** [comment]
I mean: I don't really know what you guys wanna do with that data. Frankly, I was just using the tracker and came by these issues and thought that's something I can fairly quickly contribute. I don't have that much development experience either, but I'm quite happy with the general structure of the data. Throwing new keys/values in at a later time when needed shouldn't be to difficult either. Two remarks though:
1) If there is localization needed the description should have a localization as well and at that point I don't really like the current solution with one `locales` object per top level element. The best solution that comes to my mind right now would be separate locale json files and then you simply put the key wherever localized strings are needed. Example: The `description` key gets a value of `traders.prapor.description` and in separate json files you put the actual localized values.
2) The id probably needs to be smth else but an integer between 0 and n. I saw that you gave the items their official IDs. Maybe the same is adequate and possible for the traders/everything else?

**Comment by kokarn** [comment]
Agree on localization things. 

Have had some talks with @thaddeus about good ways to do it, but nothing decided yet so let's keep it as is.

Official id's makes sense with items but not so much with traders as there's so few :)

LGTM but I'll let @thaddeus merge

**Comment by thaddeus** [comment]
Sorry for the (very) slow response to this PR. Been a struggle getting back into a nightly routine working on the data/tracker - need that imminent wipe energy :P This all looks wonderful, will be very large and helpful step towards enabling richer output for tools! Thanks a ton!

**Pull request merged**
